# Dependabot version updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "Prism.Core"
      - dependency-name: "Prism.DryIoc.Avalonia"
      - dependency-name: "MvvmAIO.Prism.SourceGenerators"
      - dependency-name: "MvvmAIO.Prism.Bcl.Commands"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps(nuget)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:05"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(ci)"
